apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: demo-web
  ports:
    - port: 80 # Cổng của Service
      targetPort: 80 # Cổng của Container bên trong Pod
      nodePort: 30080 # Cổng mở ra bên ngoài máy Mac của bạn
